apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: eoap-quickwin
profiles:
  - name: coder
    
    manifests:
      rawYaml:
      - coder-manifests/coder.yaml
      - coder-manifests/localstack.yaml
    
    deploy:

      kubectl: 
        
        flags:
          global: # additional flags passed on every command.
          - --namespace=eoap-quickwin
        hooks:
          after:
          - host:
              command: ["sh", "-c", "./wait-for-it.sh"]
              os: [darwin, linux]

    portForward:
      - resourceType: service
        resourceName: code-server-service
        namespace: eoap-quickwin  
        port: 8080
        localPort: 8000  # Port on your local machine
